version: v1
managed:
  enabled: true
  go_package_prefix:
    default: github.com/arkavo-org/opentdf-platform/protocol/go
    except:
      - buf.build/bufbuild/protovalidate
      - buf.build/googleapis/googleapis
      - buf.build/grpc-ecosystem/grpc-gateway
plugins:
  - plugin: buf.build/grpc-ecosystem/openapiv2:v2.18.1
    out: docs/openapi