version: v2
managed:
  enabled: true
  disable:
    - file_option: go_package
      module: buf.build/bufbuild/protovalidate
    - file_option: go_package
      module: buf.build/googleapis/googleapis
    - file_option: go_package
      module: buf.build/grpc-ecosystem/grpc-gateway
  override:
    - file_option: go_package_prefix
      value: github.com/opentdf/platform/protocol/go
plugins:
  - local: protoc-gen-connect-openapi
    out: docs/openapi
    opt:
      - format=yaml
