# Config documentation: https://github.com/actions/dependency-review-action?tab=readme-ov-file#configuration
name: 'Dependency Review'
on:
  pull_request: {}
  merge_group:
  workflow_call:
    inputs:
      fail-on-severity:
        description: "Minimum severity to fail job."
        default: "low"
        required: false
        type: string
      base-ref:
        description: "Base ref for building diff."
        default: ""
        required: false
        type: string
      head-ref:
        description: "Head ref for building diff."
        default: ""
        required: false
        type: string

jobs:
  dependency-review:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: "Skipping on merge queue event"
        if: ${{ github.event_name == 'merge_group' }}
        run: |
          echo "Skipping on merge queue event"

      - name: Checkout
        if: ${{ github.event_name != 'merge_group' }}
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: 'Dependency Review'
        if: ${{ github.event_name != 'merge_group' }}
        uses: actions/dependency-review-action@3c4e3dcb1aa7874d2c16be7d79418e9b7efd6261 # v4.8.2
        with:
          fail-on-severity: ${{ inputs.fail-on-severity }}
          deny-licenses: >
            GPL-2.0,
            AGPL-1.0,
            AGPL-1.0-or-later,
            AGPL-1.0-only,
            AGPL-3.0,
            AGPL-3.0-only,
            AGPL-3.0-or-later,
            GPL-1.0,
            GPL-1.0+,
            GPL-1.0-only,
            GPL-1.0-or-later,
            CNRI-Python-GPL-Compatible,
            GPL-2.0+,
            GPL-2.0-only,
            GPL-2.0-or-later,
            GPL-2.0-with-GCC-exception,
            GPL-2.0-with-autoconf-exception,
            GPL-2.0-with-bison-exception,
            GPL-2.0-with-classpath-exception,
            GPL-2.0-with-font-exception,
            GPL-3.0,
            GPL-3.0+,
            GPL-3.0-only,
            GPL-3.0-or-later,
            GPL-3.0-with-GCC-exception,
            GPL-3.0-with-autoconf-exception,
            LGPL-2.0,
            LGPL-2.0+,
            LGPL-2.0-only,
            LGPL-2.0-or-later,
            LGPL-2.1,
            LGPL-2.1+,
            LGPL-2.1-only,
            LGPL-2.1-or-later,
            LGPL-3.0,
            LGPL-3.0+,
            LGPL-3.0-only,
            LGPL-3.0-or-later,
            LGPLLR,
            NGPL
          allow-dependencies-licenses: >
            pkg:githubactions/SonarSource/sonarqube-scan-action
          comment-summary-in-pr: on-failure
          base-ref: ${{ inputs.base-ref || github.event.pull_request.base.sha || github.event.repository.default_branch }}
          head-ref: ${{ inputs.head-ref || github.event.pull_request.head.sha || github.ref }}
