name: testing

on:
  pull_request:
    branches:
      - "**"

permissions: {}

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - run: |
          echo ${{ vars.CENTRAL_WIF_PROVIDER }}

      - name: "Authenticate to Google Cloud (Push to Public registry)"
        id: "gcp-auth"
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          workload_identity_provider: ${{ vars.CENTRAL_WIF_PROVIDER }}
          project_id: ${{ vars.CENTRAL_WIF_PROJECT_ID }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v3"

      - run: |
          TOKEN_JSON=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=$AUDIENCE")
          ID_TOKEN=$(echo "$TOKEN_JSON" | jq -r .value)
          echo '```json' >>"$GITHUB_STEP_SUMMARY"
          echo "$ID_TOKEN" | awk -F. '{print $2}' | base64 -d 2>/dev/null | jq -r | tee -a "$GITHUB_STEP_SUMMARY" || true
          echo '```' >>"$GITHUB_STEP_SUMMARY"

      - name: Sign the images with GitHub OIDC Token
        run: |
          gcloud auth configure-docker us-docker.pkg.dev --quiet
          docker pull us-docker.pkg.dev/prj-opentdf-4fc4/opentdf/platform:nightly
