name: "Vulnerability Checks"

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

permissions: {}

jobs:
  vulncheck:
    permissions:
      contents: read
    name: vulncheck
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        directory:
          - examples
          - sdk
          - service
    steps:
      - name: govluncheck
        uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1.0.4
        with:
          go-version-input: "1.24.12"
          work-dir: ${{ matrix.directory }}
